variables:
  GIT_SUBMODULE_STRATEGY: recursive

name: Run commands on different operating systems
on:
  push:
    branches: [ githubCI ]
  pull_request:
    branches: [ main ]

jobs:
  Run-self-hosted:
    name: Run npm on Ubuntu
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm help

stages:
  - build
  - check
  - deploy
  - postDeploy

.only-default: &only-default
  only:
    - main
    - merge_requests
    - tags
  tags:
    - java11
  except:
    - /^.*_inhouse.*$/
    - /^.*_RC.*$/

Compile:
  <<: *only-default
  stage: build
  needs: []
  script: ./gradlew app:assembledebug --no-configuration-cache
  except:
    - tags
    - main

Test:
  <<: *only-default
  stage: check
  needs: []
  script: ./gradlew testDebugUnitTest app:testInhouseDebug --no-configuration-cache
  artifacts:
    name: Tests reports
    paths:
      - "*/build/reports"
    when: on_failure
    expire_in: 1 day
  tags:
    - java11


